const tintColor = "#F6ACC7";
const secondaryColor = "#47A6DF";
const themeColor = "#EA7773";
export default {
  tintColor,
  secondaryColor,
  themeColor,
  tabIconDefault: "#ccc",
  tabIconSelected: secondaryColor,
  tabBar: "#fefefe",
  violet: "#4b0082",
  errorBackground: "red",
  errorText: "#fff",
  warningBackground: "#EAEB5E",
  warningText: "#666804",
  noticeBackground: tintColor,
  noticeText: "#fff",
  rightAvatar: "#DCF8C6",
  redLabel: "red",
  blueLabel: "blue",
  greenLabel: "green",
  blackLabel: "black",
  marked: "pink",
  white: "#ffff",
  blue: "#50A1F1",
  helpText: "grey",
  grey: "#E7E4E4",
  labelText: "#999999",
  lightGreenChatBubble: "#DCF8C6",
  facebookBrand: "#4267B2",
  googleBrand: "#DD4B39",
  transparencyBlur: "rgba(0, 0, 0, 0.5)",
  greyBackground: "#F2F2F2",
  orange: "#ff8c00",
  sketchGreen: "#80EE8A",
  sketchOrange: "#E8783C",
  sketchYellow: "#E8E03C",
  warmOrange: "#DC7A3F",
  brickRed: "#CF5555",
  lavendarPink: "#D86181",
  orchidPink: "#F2798F",
  duskyBrown: "#F2AB9B",
  pastelPink: "#F29393",
  tintPink: "#F2C1C1",
  lightPink: "#EFC1CD",
  triadicPink: "#F4DCDD",
  saturatedPink: "#F4D9D9",
  tonedOrange: "#F29893",
  bushPink: "#EBBBBA",
  overLayFloatingButton: "rgba(68, 68, 68, 0.2)",
  dodgerBlue: "#2196F3"
};
